[server]
hostname = "localhost"
node_ip = "127.0.0.1"

[user_store]
type = "database_unique_id"

[database.shared_db]
type = "h2"
url="jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"
[database.shared_db.pool_options]
max_active = "50"
max_wait = "60000"
test_on_borrow = true
validation_interval = "30000"
default_auto_commit = true

# To seperate user data
#[database.user]
#type = "h2"
#url="jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
#username = "wso2carbon"
#password = "wso2carbon"
#[database.shared_db.pool_options]
#maxActive = "50"
#maxWait = "60000"
#testOnBorrow = true
#validationInterval = "30000"
#defaultAutoCommit = true


# To seperate config data
#[database.config]
#type = "h2"
#url="jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
#username = "wso2carbon"
#password = "wso2carbon"
#[database.shared_db.pool_options]
#maxActive = "50"
#maxWait = "60000"
#testOnBorrow = true
#validationInterval = "30000"
#defaultAutoCommit = true

#[config_data]
#path = "/_system/config/apim" to change data path
#enable_cache = true To enable data feched from config

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[keystore.primary]
file_name = "wso2carbon.jks"
type ="JKS"
password ="wso2carbon"
alias ="wso2carbon"
key_password = "wso2carbon"
[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

#[keystore.internal]
#file_name = "wso2carbon.jks"
#type ="JKS"
#password ="wso2carbon"
#alias ="wso2carbon"
#key_password = "wso2carbon"

#[admin_console.authenticator.token_ui_authenticator]
#enable = false
#priority = 5

#[admin_console.authenticator.saml_sso_authenticator]
#enable = false
#priority = 10
#login_page = "/carbon/admin/login.jsp"
#service_provider_id = "carbonServer"
#identity_provider_sso_service_url = "https://localhost:9443/samlsso"
#name_id_policy_format = "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
#assertion_consumer_service_url = "https://localhost:9443/acs"
#jit_user_provisioning_enabled = false
#super_admin_role_required = false

#[admin_console.authenticator.mutual_ssl_authenticator]
#priority = 5
#username_header
#white_list_enabled
#white_list
